RAG Guide: Comment out set_css logic that breaks for Jupyter notebooks
I noticed that this was breaking for when I was running this in Jupyter notebooks. I also noticed we had comments in the notebook saying `# Uncomment for Google Colab to ...` so figured we could do the same here. If you don't like it, no worries

## Test Plan
Before it wasn't working, and we got these errors
```
Error in callback <function set_css at 0x33e33d260> (for pre_run_cell), with arguments args (<ExecutionInfo object at 33e35b110, raw_cell="raw_documents = [
    {
        "title": "Text Emb.." store_history=True silent=False shell_futures=True cell_id=vscode-notebook-cell:/Users/rossdancraig/Projects/cohere-notebooks/notebooks/guides/RAG_with_Chat_Embed_and_Rerank_via_Pinecone.ipynb#X13sZmlsZQ%3D%3D>,),kwargs {}:

```

```
{
	"name": "TypeError",
	"message": "set_css() takes 0 positional arguments but 1 was given",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: set_css() takes 0 positional arguments but 1 was given"
}
```

Now it works!