Remove non-necessary and deprecated import
The line: `from cohere import embeddings` is not necessary
since we've already imported cohere through `import cohere`.

It leads to the error:
`ImportError: cannot import name 'embeddings' from
'cohere' (/usr/local/lib/python3.10/dist-packages/cohere/__init__.py)`.

And indeed, in that `__init__.py` file, there's no `embeddings` module
exported
(see https://github.com/cohere-ai/cohere-python/blob/main/cohere/__init__.py)